version: '3.8'
services:

  database:
    image: mariadb:latest
    container_name: database
    ports:
      - ${DB_PORT}
    volumes:
      - /var/lib/mariaDb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw