version: '3.8'

services:

  database:
    image: mariadb:latest
    container_name: database
    ports:
      - ${DB_PORT}
    volumes:
      - /var/lib/mariaDb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

  php-fpm:
    container_name: backend
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  frontend:
    build:
      context: ./../
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - php-fpm
    container_name: frontend
    ports:
      - ${NGINX_FRONT_PORT}:${NGINX_FRONT_PORT}


  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

